export const FETCH_START = 'FETCH_START';
export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const SET_MONTH_DAYS = 'SET_MONTH_DAYS';
export const UPDATE_GENERAL_PARAM = 'UPDATE_GENERAL_PARAM';
export const SELECT_DAY = 'SELECT_DAY';
